site_url: https://core.ac.uk

backend:
  name: github
  repo: oacore/content
  branch: main

  cms_label_prefix: 'âœï¸ '

  site_domain: core.ac.uk

  base_url: https://auth.oacore.vercel.app
  auth_endpoint: api/begin

  commit_messages:
    create: Create {{collection}} "{{slug}}"
    update: Update {{collection}} "{{slug}}"
    delete: Delete {{collection}} "{{slug}}"
    uploadMedia: Upload {{path}}
    deleteMedia: Delete {{path}}
  squash_merges: true

media_folder: images
public_folder: ''

publish_mode: editorial_workflow

slug:
  clean_accents: true

show_preview_links: true

collections:
- name: about

  create: false
  delete: false

  label: â„¹ï¸ About
  label_singular: section
  description: >
    All the sections on the page â€œAbout COREâ€. Sections are listed in order
    appearing on the page.

  files:
    - name: meta
      label: â„¹ï¸ Metadata (title, description, headline)
      file: about/meta.yml
      fields:
      - name: title
        widget: string
        label: Title
        hint: >
          Displayed in the browser as a tab name and in Google, when
          the page appears in the search results.
      - name: description
        widget: text
        label: Description
        hint: >
          Description of the page, not visible on the page but will be shown
          in search engines when the page appers in results. Important
          to have good performance in search engines.
      - name: headline
        widget: string
        label: Headline
        hint: >
          TheÂ title of the page. Displayed on the page below header
          andÂ above theÂ page navigation.

    - name: mission
      label: ğŸ‘ Mission
      file: about/mission.md
      fields:
      - name: title
        widget: string
        label: Title
        hint: >
          Appears above the text and video.
      - name: short-title
        widget: string
        label: Short Title
        hint:  >
          Identifies the section in the page navigation bar.
          If empty, the section won't appear in the page navigation.
      - name: video
        widget: object
        label: Video
        summary: '{{ fields.title }}'
        fields:
        - name: title
          widget: string
          label: Caption
          hint: >
            Necessary for people who cannot watch or load the video.
            Lets them understand what it is about.
        - name: src
          widget: string
          label: Link
          hint: >
            An embeddable URL for the video. When you click on â€œShareâ€ and
            then â€œEmbedâ€ on YouTube, it should be the <URL>
            inside src="<URL>"
      - name: body
        widget: markdown
        label: Content
        buttons: [bold, italic, link, quote, bulleted-list, numbered-list]

    - name: blog
      label: ğŸ“˜ Blog
      file: about/blog.md
      fields:
      - name: title
        label: Title
        widget: string
      - name: short-title
        label: Short title
        widget: string
        hint: >
          Identifies the section in the page navigation bar.
          If empty, the section won't appear in the page navigation.
      - name: action-label
        widget: string
        label: Call to action
        hint: >
          A button caption, intended to call the user view the target page.

    - name: endorsements
      label: 'ğŸ‘‰ Teaser: Endorsements'
      file: about/endorsements.md
      fields:
      - name: title
        label: Title
        widget: string
      - name: short-title
        label: Short title
        widget: string
        hint: >
          Identifies the section in the page navigation bar.
          If empty, the section won't appear in the page navigation.
      - name: body
        widget: markdown
        label: Content
        buttons: [bold, italic, link, quote, bulleted-list, numbered-list]
      - name: action-label
        widget: string
        label: Call to action
        hint: >
          A button caption, intended to call the user view the target page.
      - name: icon-url
        widget: hidden
        label: Decorative icon
        hint: >
          An icon above the section. Configured internally.
          There is no need to bother the content manager by designer things.

    - name: how-it-works
      label: âœ¨ How it works
      file: about/how-it-works.md
      fields:
      - name: title
        label: Title
        widget: string
      - name: short-title
        label: Short title
        widget: string
        hint: >
          Identifies the section in the page navigation bar.
          If empty, the section won't appear in the page navigation.
      - name: body
        label: Content
        widget: markdown
        buttons: [bold, italic, link, quote, bulleted-list, numbered-list]
      # Actions need rethinking. It's better if there is only one action only
      # per piece of content, i.e. section
      - name: action-labels
        widget: object
        label: Calls to action
        hint: >
          Button captions, intended to call the user view the target page or do
          something we want them to do.
        fields:
        - name: primary
          widget: string
          label: Primary
        - name: secondary
          widget: string
          label: Secondary

    - name: services
      label: 'ğŸ‘‰ Teaser: Services'
      file: about/services.md
      fields:
      - name: title
        label: Subsection title
        widget: string
      - name: short-title
        label: Short title
        widget: string
        hint: >
          Identifies the section in the page navigation bar.
          If empty, the section won't appear in the page navigation.
      - name: action-label
        widget: string
        label: Call to action
        hint: >
          A button caption, intended to call the user view the target page.

    - name: team
      label: ğŸ§‘â€ğŸ’» Team
      file: about/team.md
      fields:
      - name: title
        label: Title
        widget: string
      - name: short-title
        label: Short title
        widget: string
        hint: >
          Identifies the section in the page navigation bar.
          If empty, the section won't appear in the page navigation.

    - name: ambassadors
      label: 'ğŸ‘‰ Teaser: Ambassadors'
      file: about/ambassadors.md
      fields:
      - name: title
        label: Title
        widget: string
      - name: short-title
        label: Short title
        widget: string
        hint: >
          Identifies the section in the page navigation bar.
          If empty, the section won't appear in the page navigation.
      - name: body
        widget: markdown
        label: Content
        buttons: [bold, italic, link, quote, bulleted-list, numbered-list]
      - name: action-label
        widget: string
        label: Call to action
        hint: >
          A button caption, intended to call the user view the target page.
      - name: icon-url
        widget: hidden
        label: Decorative icon
        hint: >
          An icon above the section. Configured internally.
          There is no need to bother the content manager by designer things.

    - name: resources
      label: ğŸ‡ Resources
      file: about/resources.md
      fields:
      - name: title
        label: Title
        widget: string
      - name: short-title
        label: Short title
        widget: string
        hint: >
          Identifies the section in the page navigation bar.
          If empty, the section won't appear in the page navigation.

    - name: research
      label: 'ğŸ‘‰ Teaser: Research outputs'
      file: about/research.md
      fields:
      - name: title
        label: Title
        widget: string
      - name: short-title
        label: Short title
        widget: string
        hint: >
          Identifies the section in the page navigation bar.
          If empty, the section won't appear in the page navigation.
      - name: body
        widget: markdown
        label: Content
        buttons: [bold, italic, link, quote, bulleted-list, numbered-list]
      - name: action-label
        widget: string
        label: Call to action
        hint: >
          A button caption, intended to call the user view the target page.
      - name: icon-url
        widget: hidden
        label: Decorative icon
        hint: >
          An icon above the section. Configured internally.
          There is no need to bother the content manager by designer things.

  slug: '{{filename}}'

  preview_path: api/preview?page=about&ref=cms/about/{{slug}}


- name: team

  folder: team
  extension: md
  format: yaml-frontmatter

  media_folder: '/images/team'

  create: true
  delete: false

  label: ğŸ§‘â€ğŸ’»Â Team
  label_singular: team member
  summary: '{{first-name}} {{last-name}}'

  fields:
  - name: first-name
    label: First Name
    widget: string
  - name: last-name
    label: Last Name
    widget: string
  - name: role
    label: Role
    widget: string
  - name: photo
    label: Photo
    widget: file
    allow_multiple: false
    required: false
  - name: body
    widget: markdown
    buttons: [bold, italic, link, quote, bulleted-list, numbered-list]
    label: Description
    hint: >
      Try to keep this text relatively small, about 3 sentences
  - name: past
    widget: boolean
    default: false
    label: Past
    hint: >
      Toggle the switch on if the member left the team
  - name: order
    widget: hidden
    default: 0
    label: Order
    hint: >
      This is used to force sorting team members on the website in a way
      different from alphabetical. Higher numbers go first.

      Practically, this is used to make project founder go first.

  slug: '{{first-name}}-{{last-name}}'

  sortable_fields: [first-name, last-name]
  view_filters:
  - field: past
    pattern: false
    label: Current
  - field: past
    pattern: true
    label: Past

  preview_path: api/preview?page=about&ref=cms/team/{{slug}}
