site_url: https://core.ac.uk

backend:
  name: github
  repo: oacore/content
  branch: main
  
  cms_label_prefix: 'âœï¸ '

  site_domain: core.ac.uk

  base_url: https://auth.oacore.vercel.app
  auth_endpoint: api/begin

  commit_messages:
    create: Create {{collection}} "{{slug}}"
    update: Update {{collection}} "{{slug}}"
    delete: Delete {{collection}} "{{slug}}"
    uploadMedia: Upload {{path}}
    deleteMedia: Delete {{path}}
  squash_merges: true

media_folder: images
public_folder: ''

publish_mode: editorial_workflow

slug:
  clean_accents: true

show_preview_links: true

collections:
- name: team

  folder: team
  extension: md
  format: yaml-frontmatter

  media_folder: '/images/team'

  create: true
  delete: false

  label: ðŸ§‘â€ðŸ’»Â Team
  label_singular: team member
  summary: '{{first-name}} {{last-name}}'

  fields:
  - name: first-name
    label: First Name
    widget: string
  - name: last-name
    label: Last Name
    widget: string
  - name: role
    label: Role
    widget: string
  - name: photo
    label: Photo
    widget: file
    allow_multiple: false
    required: false
  - name: body
    widget: markdown
    buttons: [bold, italic, link, quote, bulleted-list, numbered-list]
    label: Description
    hint: >
      Try to keep this text relatively small, about 3 sentences
  - name: past
    widget: boolean
    default: false
    label: Past
    hint: >
      Toggle the switch on if the member left the team
  - name: order
    widget: hidden
    default: 0
    label: Order
    hint: >
      This is used to force sorting team members on the website in a way
      different from alphabetical. Higher numbers go first.

      Practically, this is used to make project founder go first.

  slug: '{{first-name}}-{{last-name}}'

  sortable_fields: [first-name, last-name]
  view_filters:
  - field: past
    pattern: false
    label: Current
  - field: past
    pattern: true
    label: Past

  preview_path: api/preview?page=about&ref=cms/team/{{slug}}


- name: history

  folder: history
  extension: md
  format: yaml-frontmatter

  media_folder: '/images/history'

  create: true
  delete: true

  label: ðŸ•° History
  label_singular: milestone
  summary: '{{date}} - {{title}}'

  fields:
  - name: date
    label: Date
    widget: datetime
    format: YYYY-MM-DD
    date_format: YYYY-MM-DD
    time_format: ''
    default: ''
    hint: >
      All milestones on the page are sorted in chronologic order.
      The day is not displayed, therefore it doesn't have to be correct.
    picker_utc: true
  - name: title
    label: Milestone
    widget: string
    hint: >
      The title for the milestone
  - name: body
    widget: markdown
    buttons: [bold, italic, link, quote, bulleted-list, numbered-list]
    label: Description
    hint: >
      Try to keep this concise, it should be approximately 2-3 lines on the website.
  - name: image
    label: Image
    widget: object
    summary: 'Image: {{alt}}'
    hint: >
      A good illustration of what the milestone is about.
      Despite it being optional, having illustrations is preferable.
    fields:
      - name: src
        label: Source
        widget: image
        allow_multiple: false
        required: false
        hint: >
          Provide a link to the image or upload as a file.
      - name: alt
        widget: string
        required: false
        label: Alternative text
        hint: >
          Description of what is actually displayed on the image.
          It helps tech-assistive users who can't see the screen understand
          what is on the picture.
  - name: link
    label: Link
    hint: >
      The link to a relevant resource
    widget: object
    fields:
      - name: href
        label: URL
        widget: string
      - name: caption
        label: Caption
        widget: string
      - name: description
        label: Description
        widget: string
        required: false
      - name: source
        label: Source
        widget: string

  slug: '{{date}}-{{title}}'

  sortable_fields: [date, title]

  preview_path: api/preview?page=history&ref=cms/history/{{slug}}
